### ISSUE TITLE
Version de geonature installables via docker

### ISSUE THREAD

**Issue by mathieubossaert** [PnX-SI/GeoNature-Docker-PNX#7]
Bonjour,

Merci pour ce travail de dockerisation de geonature.

Toutes les versions sont-elles installations via docker en spécifiant le numéro de version dans le fichier env ?
Ou doit-on se conformer à une liste d'images disponibles ? Et laquelle le cas échéant ?

**Comment by hypsug0** [comment]
Bonjour @mathieubossaert , je suis en train de travailler sur une version publiable sur [mon fork](https://github.com/dbwildlife/GeoNature-docker) pour une prochaine PR, le compose est basé sur l'image PostGIS (v13). L'image pour la v2.6.0 est ici (version 2.6.0-env): https://hub.docker.com/r/dbwildlife/geonature/tags?page=1&ordering=last_updated

Mon docker-compose (avec traefik):
```yaml
version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4:4.27
    container_name: ${CONTAINER_PREFIX}_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - geonat


  db:
    image: postgis/postgis:13-master
    container_name: ${CONTAINER_PREFIX}_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
        #- ALLOW_IP_RANGE=0.0.0.0/0
        #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,"uuid-ossp","pg_trgm","postgis_raster"
        #- EXTRA_CONF=datestyle='ISO, DMY'
    volumes:
      - ${PGDATA_DIR}:/var/lib/postgresql
      - ${GEONATURE_COMMON_DIR}:/geonature
    networks:
      - geonat


  geonature:
    image: ${GEONATURE_IMAGE}
    container_name: ${CONTAINER_PREFIX}_geonature
    volumes:
      - ${GEONATURE_COMMON_DIR}:/geonature
    environment:
      - GEONATURE_PROTOCOL=${GEONATURE_PROTOCOL}
      - GEONATURE_DOMAIN=${GEONATURE_DOMAIN}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - http_proxy=${HTTP_PROXY}
      - https_proxy=${HTTP_PROXY}
    depends_on:
      - db
    networks:
      - geonat

  proxy:
    image: nginx:1.17-alpine
    container_name: ${CONTAINER_PREFIX}_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${GEONATURE_COMMON_DIR}:/geonature
    environment:
      - "VIRTUAL_HOST=${GEONATURE_DOMAIN}"
    depends_on:
      - geonature
    labels:
      - traefik.http.routers.geonature.rule=Host(`geonature.dbwildlife.info`)
      - traefik.http.routers.geonature.tls.certresolver=le
      - traefik.http.routers.geonature.entrypoints=web-secure
      - traefik.http.middlewares.geonature.redirectscheme.scheme=https
      - traefik.http.middlewares.geonature.redirectscheme.permanent=true
      - traefik.http.middlewares.geonature.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    networks:
      - geonat
      - front

networks:
  geonat:
    driver: bridge
  front:
    name: front
    external: true

```
le fichier .env
```ini
CONTAINER_PREFIX=gn_
POSTGRES_DB=geonature
POSTGRES_USER=geonature
POSTGRES_PASS=myDbPwd
POSTGRES_PORT=5432
PGDATA_DIR=/path/to/pg/data/files
GEONATURE_DOMAIN=mydomain.org
GEONATURE_PROTOCOL=https
GEONATURE_IMAGE=dbwildlife/geonature:2.6.0-env
GEONATURE_COMMON_DIR=/path/to/geonature/install/volume
PGADMIN_DEFAULT_EMAIL=admin@mydomain.org
PGADMIN_DEFAULT_PASSWORD=myPgAdminPwd
USE_PROXY=0
HTTP_PROXY=''
HTTPS_PROXY=''
NGINX_CONF=./nginx.conf
BOOTSTRAP_DIR=''
```
Le fichier nginx est le même que celui du dépot.
